### ISSUE TITLE
RFC: It's about time to enable Tauri updater.

### ISSUE THREAD

**Issue by kidylee** [tw93/Pake#549]
### Search before asking

- [X] 我在 [issues](https://github.com/tw93/Pake/issues?q=) 列表中搜索，没有找到类似的内容。
I searched in the [issues](https://github.com/tw93/Pake/issues?q=) and found nothing similar.

### Motivation

Auto updating Pake itself is the must feature for the user who like to keep their software up to date to get the most joyful user experience.

#### Prerequisite 
These tasks need @tw93 as admin to do the setup
- [ ] user `npm run tauri signer generate -- -w ~/.tauri/myapp.key` generate pubkey and privkey
- [ ] Add these keys into secret of this repo: `PAKE_TAURI_PUBLIC_KEY` and `PAKE_TAURI_PRIVATE_KEY`

#### TODO
- [ ] Enable signing when build apps
- [ ] Host a release file in seperated branch
- [ ] Enable updater for each apps.

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by tw93** [comment]
赞 很欢迎提交pr

**Comment by tw93** [comment]
Here I thought carefully, in fact, there is no need to update the Pake, because most of the logic is all in the web page to carry, basically, there will be no problem, increase the update can only meet the common package scenarios, for the packaged scenarios, the configuration will be more troublesome, and it seems that there is no need to update the thing, do you think so?

**Comment by kidylee** [comment]
I would like it keeps itself up to date automatically, especially when Pake has major issue fix or fantastic feature released, instead of re-download it from github.

I encountered one issue where the message will accidentally send to ChatGPT when I hit enter key during inputting Chinese words. I know it will be fixed in the future, but don't know when, so it would be great that it will update it self with fix when I open it in next time on my computer.

I'm not sure how many this kind of issues over these, if it is a rare case, I'm ok with close this issue at this moment.
